
name: compiling kernel

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
env:
  USERNAME: Area69Lab 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           - uses: rokibhasansagar/slimhub_actions@main
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean
           sudo install telegram /usr/bin
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python clang libssl-dev rsync flex bison ccache
            mkdir ~/bin && PATH=~/bin:$PATH && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
       - name: Downloading script from remote repo
         run: |
            wget https://raw.githubusercontent.com/flashokillerify/personalscripts/master/kernel/build_ci.sh
            bash build_ci.sh
